change: Jenkinsfile and Jenkinsfile_deploy

diff --git a/Jenkinsfile_deploy b/Jenkinsfile_deploy
--- a/Jenkinsfile_deploy
+++ b/Jenkinsfile_deploy
@@ -1,22 +1,59 @@
 @Library('my-shared-lib@main') _
 
 pipeline {
-    agent { 
-        label "${params.ENVIRONMENT}" 
+    agent { label "${params.ENVIRONMENT}" }
+    
+    options {
+        timestamps()
     }
-
+    
     stages {
-        stage('Deploy Application') {
+        stage('Pull Image') {
             steps {
-                echo "Deploying version ${params.IMAGE_TAG} to ${params.ENVIRONMENT}"
-                sh "docker stop app || true && docker rm app || true"
-                sh "docker run -d --name app -p 8000:8000 m_filatova/app:${params.IMAGE_TAG}"
+                script {
+                    echo "Pulling image m_filatova/app:${params.IMAGE_TAG} on ${params.ENVIRONMENT}"
+                    sh "docker pull mfilatova/currency-rest-api:${params.IMAGE_TAG}"
+                }
             }
         }
-        stage('Verify') {
+        
+        stage('Deploy Container') {
             steps {
-                runSmokeTest("http://localhost:8000/info")
+                script {
+                    echo "Stopping old container..."
+                    sh 'docker stop app-main || true'
+                    sh 'docker rm app-main || true'
+                    
+                    echo "Starting new container..."
+                    sh "docker run -d --name app-main -p 8000:8000 mfilatova/currency-rest-api:${params.IMAGE_TAG}"
+                    
+                    echo "Waiting for container to start..."
+                    sh 'sleep 5'
+                    sh 'docker ps | grep app-main'
+                }
             }
+        }
+        
+        stage('Smoke Test') {
+            steps {
+                script {
+                    // Вызов функции из Shared Library
+                    runSmokeTest('http://localhost:8000/info')
+                    runSmokeTest('http://localhost:8000/info/currency?currency=USD&date=2023-01-17')
+                }
+            }
+        }
+    }
+    
+    post {
+        always {
+            echo "=== Container logs ==="
+            sh 'docker logs app-main || true'
+        }
+        failure {
+            echo "Deployment failed! Cleaning up..."
+            sh 'docker stop app-main || true'
+            sh 'docker rm app-main || true'
         }
     }
 }
