refactor: scripted pipeline with docker-compose

diff --git a/Jenkinsfile_deploy b/Jenkinsfile_deploy
--- a/Jenkinsfile_deploy
+++ b/Jenkinsfile_deploy
@@ -1,59 +1,40 @@
 @Library('my-shared-lib@main') _
 
-pipeline {
-    agent { label "${params.ENVIRONMENT}" }
-    
-    options {
-        timestamps()
-    }
-    
-    stages {
-        stage('Pull Image') {
-            steps {
-                script {
-                    echo "Pulling image m_filatova/app:${params.IMAGE_TAG} on ${params.ENVIRONMENT}"
-                    sh "docker pull mfilatova/currency-rest-api:${params.IMAGE_TAG}"
-                }
+node(params.ENVIRONMENT) {
+    timestamps {
+        try{
+            stage('Pull Image') {
+                echo "Pulling image mfilatova/currency-rest-api:${params.IMAGE_TAG} on ${params.ENVIRONMENT}"
+                sh "docker pull mfilatova/currency-rest-api:${params.IMAGE_TAG}"
+            }
+            
+            stage('Deploy Container') {
+                echo "Stopping old container..."
+                sh 'docker-compose down || true'
+                        
+                echo "Starting new container with tag ${params.IMAGE_TAG}..."
+                sh "IMAGE_TAG=${params.IMAGE_TAG} docker-compose up -d"
+                        
+                echo "Waiting for container to start..."
+                sh 'sleep 5'
+                sh 'docker-compose ps'
+            }
+            
+            stage('Smoke Test') {
+                runSmokeTest('http://localhost:8000/info')
+                runSmokeTest('http://localhost:8000/info/currency?currency=USD&date=2023-01-17')
             }
         }
-        
-        stage('Deploy Container') {
-            steps {
-                script {
-                    echo "Stopping old container..."
-                    sh 'docker stop app-main || true'
-                    sh 'docker rm app-main || true'
-                    
-                    echo "Starting new container..."
-                    sh "docker run -d --name app-main -p 8000:8000 mfilatova/currency-rest-api:${params.IMAGE_TAG}"
-                    
-                    echo "Waiting for container to start..."
-                    sh 'sleep 5'
-                    sh 'docker ps | grep app-main'
+        finally{
+            stage('Post Actions'){
+                echo "=== Container logs ==="
+                sh 'docker-compose logs || true'
+
+                if (currentBuild.result == 'FAILURE') {
+                    echo "Deployment failed! Cleaning up..."
+                    sh 'docker-compose down || true'
                 }
             }
-        }
-        
-        stage('Smoke Test') {
-            steps {
-                script {
-                    // Вызов функции из Shared Library
-                    runSmokeTest('http://localhost:8000/info')
-                    runSmokeTest('http://localhost:8000/info/currency?currency=USD&date=2023-01-17')
-                }
-            }
-        }
-    }
-    
-    post {
-        always {
-            echo "=== Container logs ==="
-            sh 'docker logs app-main || true'
-        }
-        failure {
-            echo "Deployment failed! Cleaning up..."
-            sh 'docker stop app-main || true'
-            sh 'docker rm app-main || true'
         }
     }
 }
